---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- GitHub:
    - HomeLab:
        - abbr: GH
          href: https://github.com/malcolmry-el/HomeLab
