title: Malcolm's HomeLab

background:
  image: https://images.unsplash.com/photo-1518770660439-4636190af475
  blur: sm
  saturate: 50
  brightness: 40
  opacity: 40

theme: dark

headerStyle: boxed

layout:
  Infrastructure:
    style: row
    columns: 3

  Monitoring:
    style: row
    columns: 3

  Network:
    style: row
    columns: 2

  Development:
    style: row
    columns: 1
