---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:

    - Portainer:
        href: https://192.168.50.2:9443
        description: Docker Management
        icon: portainer.png

    - Uptime Kuma:
        href: http://192.168.50.2:3001
        description: Monitoring
        icon: uptime-kuma.png

    - Homepage:
        href: http://192.168.50.2:3000
        description: Dashboard
        icon: homepage.png
