---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: full
      timeStyle: medium

- resources:
    cpu: true
    memory: true
    disk: /

- openmeteo:
    label: Kitchener
    latitude: 43.4516
    longitude: -80.4925
    timezone: America/Toronto
    units: metric
